galxy25/pdxCoders

TeamContracts/LauraDeWitt'sContract.txt

[Finishes #92269312]

---

TeamContracts/brandonisom'sContract.txt

[Finishes #92269224]
All hail our robot overlords!

[#92269224] Submitting contract signature for Brandon Isom.

---

Meetings/Meeting2Agenda.txt

-Reorder presentation order
-Fill in meeting location and time details.

[#none] Update Meeting 2 agenda

---

UEBPrep/app/controllers/sessions_controller.rb
UEBPrep/app/controllers/users_controller.rb
UEBPrep/app/views/layouts/application.html.erb
UEBPrep/app/views/users/_footer_links.html.erb
UEBPrep/app/views/users/edit.html.erb
UEBPrep/app/views/users/show.html.erb
UEBPrep/config/routes.rb

Fixes https://www.pivotaltracker.com/story/show/98420126

[Delivers #98420126]

---

UEBPrep/app/controllers/users_controller.rb
UEBPrep/app/views/layouts/application.html.erb
UEBPrep/config/routes.rb
UEBPrep/spec/controllers/user_controller_spec.rb
UEBPrep/spec/spec_helper.rb

-Adds test coverage for existing user controller methods. 
-Adds devise filters to user actions

[Delivers #98422270] Features/users controller spec 98422270

---

circle.yml

Revert hotfix to get our git flow back in working order.

Revert hotfix to get our git flow back in working order.

---

UEBPrep/Gemfile
UEBPrep/Gemfile.lock
UEBPrep/app/controllers/omniauth_callbacks_controller.rb
UEBPrep/app/models/user.rb
UEBPrep/app/views/sessions/new.html.erb
UEBPrep/app/views/users/new.html.erb
UEBPrep/config/initializers/devise.rb

[Finishes #9807212] Add Facebook signin/account creation

---

UEBPrep/app/views/sessions/new.html.erb
UEBPrep/app/views/users/new.html.erb

Found merge conflict descriptors in sessions/new.html.erb and users/new.html.erb. Fixed up merge conflicts, should be working right now.

Found some merge conflict stuff in the login and signup pages. Fixed, hopefully.

---

Resources/ProjectDocumentation.txt

See https://www.pivotaltracker.com/story/show/98887054
Developer Documentation
- Adds section explaining how cards are represented in the database and as objects 
- Adds section explaining how card content (text content and titled card content) are represented in the database and as objects
User Documentation
- The card creation section in the user documentation seems to cover this task already.

[#98887054] Add documentation for cards.

---

UEBPrep/app/views/devise/confirmations/new.html.erb
UEBPrep/app/views/devise/mailer/confirmation_instructions.html.erb
UEBPrep/app/views/devise/mailer/reset_password_instructions.html.erb
UEBPrep/app/views/devise/mailer/unlock_instructions.html.erb
UEBPrep/app/views/devise/passwords/edit.html.erb
UEBPrep/app/views/devise/passwords/new.html.erb
UEBPrep/app/views/devise/registrations/edit.html.erb
UEBPrep/app/views/devise/registrations/new.html.erb
UEBPrep/app/views/devise/sessions/new.html.erb
UEBPrep/app/views/devise/shared/_links.html.erb
UEBPrep/app/views/devise/unlocks/new.html.erb
UEBPrep/app/views/layouts/application.html.erb

See https://www.pivotaltracker.com/story/show/99001122
-Fixes alerts and notices staying from page to page. 
-Clears all old flash messages when you navigate to a new page. 
-Add devise views visible to all developers to be able to edit/style as need be. 
cc @ellecdwt

Bugs/alerts persists [Delivers #99001122]

---

UEBPrep/app/views/layouts/application.html.erb

See, https://www.pivotaltracker.com/story/show/99439416
- Added /'s to fix images not loading in some views.

[#99439416] Added /'s to fix images not loading. Yep.

---

UEBPrep/app/views/cards/_image_card_content.erb
UEBPrep/db/seeds.rb

param. Added image card contenttype to seeds

[#99001290] Fixed up the image card partial to use passed in content

---

UEBPrep/app/assets/stylesheets/user.css
UEBPrep/app/views/cards/_image_card_content.erb
UEBPrep/app/views/cards/_text_content.html.erb
UEBPrep/app/views/cards/_titled_card_content.erb
UEBPrep/app/views/cards/new.html.erb
UEBPrep/app/views/cards/show.html.erb

the cards are now bigger, the header is almost the full length of the
card, and the font is much larger. Also fixed the layout for the image
card so it looks nice.

card css changes

---

UEBPrep/app/assets/stylesheets/sessions.css
UEBPrep/app/views/homepage/index.html.erb
UEBPrep/app/views/layouts/application.html.erb
UEBPrep/app/views/sessions/new.html.erb
UEBPrep/app/views/users/edit.html.erb
UEBPrep/app/views/users/new.html.erb
UEBPrep/app/views/users/show.html.erb

I added ARIA tags, landmarks and I changed the alt text for images. This is only the most basic features of ARIA being used here. 
We can add more features later to increase the accessibility. Also when we start getting into more complicated pages then we will need more complicated ARIA. 
This code should not change any functionality.

Features 98394394 aria taggged pages

---

UEBPrep/app/controllers/users_controller.rb
UEBPrep/app/views/users/show.html.erb

See https://www.pivotaltracker.com/n/projects/1316386/stories/99480914
Added the playlists for the current user in the user controller
Updated the show profile to have a box to the left of the general profile info that contains all of the user's playlists.
This shows each playlist name and the number of cards in that playlist per row
Everything works, we currently only have 1 playlist to test on, but it should work fine for multiple. Can adjust it later if it doesn't once we have the ability to add/create playlists in the app.
There is a small amount of css that needs to be adjusted in order to line up the 2 divs properly, right now the profile info has a bit of weird empty padding at the top, but otherwise it looks nice.

Features/playlist profile [Delivers #99480914]

---

UEBPrep/Gemfile
UEBPrep/Gemfile.lock
UEBPrep/app/assets/javascripts/application.js
UEBPrep/app/assets/stylesheets/application.css
UEBPrep/app/views/cards/_footer.html.erb
UEBPrep/app/views/cards/show.html.erb
UEBPrep/config/initializers/social_share_button.rb
UEBPrep/config/locales/social_share_button.en.yml
UEBPrep/config/locales/social_share_button.zh-CN.yml
UEBPrep/config/locales/social_share_button.zh-TW.yml

See https://www.pivotaltracker.com/story/show/99001528
- Added partial for card footer links.
- Added render in card show for footer links.
- Added and configured social-share-button gem.
- Added share functionality for fb twitter g+ via social-share-button gem.

[#99001528] Add a link footer for cards.

---

UEBPrep/Gemfile

Client-side-validation gem not currently implemented.

Remove unimplemented gem

---

UEBPrep/app/controllers/playlists_controller.rb
UEBPrep/app/views/playlists/_show_playlist.html.erb
UEBPrep/app/views/playlists/show.html.erb
UEBPrep/app/views/users/show.html.erb
UEBPrep/spec/controllers/playlists_controller_spec.rb

See: https://www.pivotaltracker.com/story/show/99480744 
Adds show view for playlist
Able to navigate forward and back among the playlist. 
Adds spec for playlist show method and playlist show behavior. 
cc: @galxy25 @ellecdwt @brangisom @parkerBerger @stewarj  @d1str0 @caesarfish

Features/playlist show view [#Delivers 99480744]

---

UEBPrep/app/controllers/playlists_controller.rb

[Finishes #99480744] Slight refactor.

---

UEBPrep/app/controllers/sessions_controller.rb
UEBPrep/app/models/user.rb
UEBPrep/app/views/devise/registrations/new.html.erb
UEBPrep/app/views/devise/sessions/new.html.erb
UEBPrep/app/views/sessions/new.html.erb
UEBPrep/app/views/users/new.html.erb
UEBPrep/config/initializers/devise.rb

Changes login to use username instead of email for authentication

Feature/reconfig login [Delivers #99806548]

---

Resources/ProjectDocumentation.txt
UEBPrep/app/controllers/application_controller.rb
UEBPrep/app/controllers/homepage_controller.rb
UEBPrep/app/models/user.rb
UEBPrep/app/views/homepage/stats.html.erb
UEBPrep/config/routes.rb

see: https://www.pivotaltracker.com/story/show/100939580
Adds a publicly viewable page where you can see application level user activity stats. 
cc: @geekindapink @ellecdwt @brangisom @parkerBerger @caesarfish

[Delivers #100939580] Active Users Stat

---

UEBPrep/app/assets/stylesheets/cards.css
UEBPrep/app/assets/stylesheets/user.css
UEBPrep/app/views/cards/_image_card_content.erb
UEBPrep/app/views/cards/_links.html.erb
UEBPrep/app/views/cards/_text_content.html.erb
UEBPrep/app/views/cards/_titled_card_content.erb
UEBPrep/app/views/cards/examples.html.erb
UEBPrep/app/views/cards/index.html.erb
UEBPrep/app/views/cards/new.html.erb
UEBPrep/app/views/cards/show.html.erb
UEBPrep/app/views/playlists/edit.html.erb
UEBPrep/app/views/playlists/show.html.erb
UEBPrep/app/views/users/edit.html.erb
UEBPrep/app/views/users/show.html.erb

1. Biggest change is the Card Creator improvements.
2. I added the import multiple cards feature into the card creator page.
3. I added a tutorial on how to creat a .csv file onto the card creator page because Holly asked us how to create a .csv file.
4. I removed the import multiple cards from the 'Show' card page.
5. I changed the look of the delete button.
6. I ensured that every footer link was actually a link in the nav bar or somewhere more intuitive on the website. 
7. I checked everything for errors.

UI Fixes & Improvements 100974462
